### ISSUE TITLE
No encuentro el nombre del método de autenticación

### ISSUE THREAD

**Issue by joseluiscadena** [FacturAPI/facturapi-docs#122]
Quiero probar su API, pero no encuentro por ningún lado el nombre del método de autenticación, en su documentación no lo escriben, lo colocan de la siguiente manera:
![image](https://github.com/FacturAPI/facturapi-docs/assets/1645922/abf3e9ed-d34b-44e0-b762-4d2f4d0e248e)
En su referencia del API tampoco tienen un apartado de autenticación, les comparto un ejemplo de un competidor que tienen y que si comparte esto
![image](https://github.com/FacturAPI/facturapi-docs/assets/1645922/8f5d9ef5-53ff-4d7e-b2cf-6c9cdbd30765)
Si no contamos con el nombre del método, (que intente adivinarlo pensando que es auth) no es posible probar nada.

De igual forma las referencias en sus guías son de versión 1 y su API ya devuelve que v1 esta deprecada,
en fin ya me contacte con comercial de su lado pero desde ayer en la tarde no me responden.

**Comment by javorosas** [comment]
Hola @joseluiscadena . Ojo, la segunda imagen **no** es nuestra documentación. Nosotros somos Facturapi.

En la primera imagen sí, lo que representa <endpoint_method> es que no es un endpoint en específico, sino que en cada llamada a cualquier endpoint de la API debes incluir el header "Authorization"

Voy a cerrar este issue. Siéntete libre de volver a abrirlo si sigues teniendo algún otro problema

**Comment by joseluiscadena** [comment]
Que tal, ya terminamos la integración con ustedes todo ok, estaba confundiendo como funcionaba su autenticación, pense que tenías que crear un token primero cada vez que se usa el API con un endpoint exclusivo de autenticación, pero no, ya checamos y vimos como se usa, todo bien de momento gracias
