### ISSUE TITLE
Error al registrarse en la pagina

### ISSUE THREAD

**Issue by enriqueFcoG** [FacturAPI/facturapi-docs#66]
Muestra el campo phone como requerido pero no hay ningún input para agregar esa información 

![Captura de Pantalla 2022-11-24 a la(s) 15 49 45](https://user-images.githubusercontent.com/33667358/203875617-effdd0cc-89a3-4f4b-8296-c44cf9144414.png)

**Comment by javorosas** [comment]
Este error ya quedó corregido. Gracias @enriqueFcoG  por el reporte
