### ISSUE TITLE
Error while trying delete an invoice 

### ISSUE THREAD

**Issue by hectorcubillos** [FacturAPI/facturapi-docs#68]
Hi there!
By following the documentation of curl requests.
I'm facing following error message while I'm trying to cancel an invoice.

REQUEST:
curl --location --request DELETE 'https://www.facturapi.io/v2/invoices/63c9a2debab427001b7b6661?motive=02' \
--header 'Authorization: Bearer _tokenNumber_'

RESPONSE:
{
    "message": "Invoice validation failed: cancellation.status: `null` is not a valid enum value for path `cancellation.status`.",
    "ok": false
}

Thanks, 
Hector

**Comment by javorosas** [comment]
Hola @hectorcubillos , seguiste teniendo este problema?

**Comment by javorosas** [comment]
Cerrando porque no se ha reportado que el error haya seguido ocurriendo
